services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host_files'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.meminfo'
    pid: host
    restart: on-failure:3
    volumes:
      - '/:/host_files:ro,rslave'
    networks:
      - web
    read_only: true
    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - web

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/node-exporter-full.json
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - web

volumes:
  prometheus-data:
  grafana-data:

networks:
  web:
    external: true